#Numpy

In [2]:
import numpy as np

numpy vs list

In [ ]:
from time import process_time

time taken by a list

In [ ]:
ls1=[i for i in range (100000)]
start_time= process_time()
ls2=[i+5 for i in ls1]
end_time=process_time()
print(end_time-start_time)


0.008440983000000735


time taken by numpy array

In [ ]:
nm_arr = np.array([i for i in range (100000)])
start_time = process_time()
nm_arr+=5
end_time=process_time()
print(end_time-start_time)

0.00029290499999934383


Numpy Arrays

In [ ]:
np_ar = np.array([1,2,3,4])
print(np_ar)
type(np_ar)

[1 2 3 4]


numpy.ndarray

In [ ]:
np_ar.shape


(4,)

In [ ]:
b=np.array([(1,2),(3,4),(5,6)])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
b.shape

(3, 2)

In [ ]:
c= np.array([(1,2,3),(4,5,6)],dtype=float)

print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


initial placeholders in numpy array

array with zeros

In [ ]:
x= np.zeros((4,1))
print(x)

[[0.]
 [0.]
 [0.]
 [0.]]


array with one

In [ ]:
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Array with particular value

In [ ]:
z=np.full((3,4),(5))
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


Identy matrix

In [ ]:
id=np.eye((4))
print(id)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


array with random values

In [ ]:
rdm=np.random.random((3,4))
print(rdm)


[[0.65341077 0.44420248 0.22320104 0.87297184]
 [0.51228129 0.76290991 0.02476071 0.08373012]
 [0.27698142 0.700836   0.06440225 0.08456221]]


In [ ]:
rdm2=np.random.randint(10,100,(3,4))
print(rdm2)

[[91 72 98 26]
 [99 38 39 79]
 [73 98 46 43]]


array evenly spaced values ---specifying nmbrs of value required

In [ ]:
ln =np.linspace(10,30,5)
print(ln)

[10. 15. 20. 25. 30.]


array evenly spaced values ---specifying the steps

In [ ]:
ln2= np.arange(10,30,5)
print(ln2)

[10 15 20 25]


Convert a list to a numpy array

In [ ]:
lst1=[1,2,3,4]
np_ar = np.asarray(lst1)
print(np_ar)
type(np_ar)

[1 2 3 4]


numpy.ndarray

Analysing a numpy array

In [9]:
c= np.random.randint(10,100,(5,5))
print(c)
print(c.shape)
#number of dimansion
print(c.ndim)
print(c.size)#number of elements
print(c.dtype)

[[97 53 71 12 38]
 [11 94 34 45 60]
 [66 33 55 13 18]
 [93 35 60 46 74]
 [30 90 80 36 86]]
(5, 5)
2
25
int64


Mathmetical operation in np array

In [10]:
ls1=[1,2,3,4,5]
ls2=[6,7,8,9,10]
print(ls1+ls2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [15]:
nls1=np.random.randint(0,10,(3,3))
print(nls1)
nls2 = np.random.randint(10,20,(3,3))
print(nls2)
print(nls1+nls2)
print(np.add(nls1,nls2))

[[1 8 9]
 [0 8 7]
 [1 6 9]]
[[18 11 10]
 [17 19 11]
 [16 12 14]]
[[19 19 19]
 [17 27 18]
 [17 18 23]]
[[19 19 19]
 [17 27 18]
 [17 18 23]]


Array manupulation

In [19]:
ar=np.random.randint(0,10,(2,3))
print(ar)
print(ar.shape)
tp=np.transpose(ar)
print(tp)
print(tp.shape)
tp2=ar.T
print(tp2)
print(tp2.shape)

[[2 0 3]
 [5 6 7]]
(2, 3)
[[2 5]
 [0 6]
 [3 7]]
(3, 2)
[[2 5]
 [0 6]
 [3 7]]
(3, 2)


In [23]:
#re-shaping array
a= np.random.randint(0,10,(2,3))
print(a)
print(a.shape)
b=a.reshape(3,2)
print(b)
print(b.shape)

[[3 4 1]
 [5 2 6]]
(2, 3)
[[3 4]
 [1 5]
 [2 6]]
(3, 2)
